### ISSUE TITLE
ApiClient作成

### ISSUE THREAD

**Issue by nshiba** [nshiba/EatSenjuAndroid#3]
通信部分
retrofitを使う

**Comment by nshiba** [comment]
endpoint
https://script.googleusercontent.com/macros/echo?user_content_key=o_cTUl6CMCaW0Sg2DeMpfjBvWDI6o67Nut8E0V_zKbcg8P8GkYNkpGoTJdP7Mz57Gf8Bgj9AANDal0yq0aW97sQMbkfg5V-Jm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnNqPwCBRGAH-PcBEmKBDalnk0NgqNnBCCMaefBU1k4FbNaVrruTrUcrw-jBN-VFVfNveWPraiRQB&lib=MPuixP1oMDpjlDIdT_bqVlAwJX0hRdcSS

**Comment by nshiba** [comment]
データ本体
https://docs.google.com/spreadsheets/d/1FNCo_BrZ7i0Prt4gWN1Y_aW2nD_GyfuYwTiatC23c84/edit#gid=0

**Comment by munisystem** [comment]
```
@GET("macros/echo?user_content_key=o_cTUl6CMCaW0Sg2DeMpfjBvWDI6o67Nut8E0V_zKbcg8P8GkYNkpGoTJdP7Mz57Gf8Bgj9AANDal0yq0aW97sQMbkfg5V-Jm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnNqPwCBRGAH-PcBEmKBDalnk0NgqNnBCCMaefBU1k4FbNaVrruTrUcrw-jBN-VFVfNveWPraiRQB&lib=MPuixP1oMDpjlDIdT_bqVlAwJX0hRdcSS")
void fetchStore(Callback<StoreResponse> callback)
```
